jyteaches/apps/courses/urls.py
from django.conf.urls import url
from jyteaches.settings import MEDIA_ROOT,MEDIA_URL   #
from django.conf.urls.static import static            #引入media及static
from .views import CourseLisrView,CourseDetailView,CourseInfoView,CourseCommentView,AddCommentView

urlpatterns = [

    url(r'^course_list/$',CourseLisrView.as_view(),name='course_list'),
    url(r'^course_detail/(?P<course_id>.*)/$',CourseDetailView.as_view(),name='course_detail'),
    url(r'course_video/(?P<course_id>.*)/$',CourseInfoView.as_view(),name='course_video'),
    url(r'course_comment/(?P<course_id>.*)/$',CourseCommentView.as_view(),name='course_comment'),
    url(r'add_comment/$',AddCommentView.as_view(),name='add_comment'),
]+static(MEDIA_URL,document_root=MEDIA_ROOT)     #引入media

jyteaches/apps/organizations/urls.py
from django.conf.urls import url,include
from jyteaches.settings import MEDIA_ROOT,MEDIA_URL   #
from django.conf.urls.static import static            #引入media及static
from organizations.views import orglist,userask,orghome,orgcourse,orgdesc,orgteacher,user_fav,TeacherListView,TeacherDetailView

urlpatterns = [
    url(r'^orglist/$',orglist.as_view(),name='orglist'),
    url(r'^userask/$',userask.as_view(),name='userask'),
    url(r'^orghome/(?P<org_id>.*)/$',orghome.as_view(),name='orghome'),  #(?P<org_id>.*)这部分内容写错，当在前端引入url时会报错
    url(r'^orgcourse/(?P<org_id>.*)/$',orgcourse.as_view(),name='orgcourse'),
    url(r'^orgdesc/(?P<org_id>.*)/$',orgdesc.as_view(),name='orgdesc'),
    url(r'^orgteacher/(?P<org_id>.*)/$',orgteacher.as_view(),name='orgteacher'),
    url(r'^add_fav/$',user_fav.as_view(),name='add_fav'),
    url(r'^teacher_list/$',TeacherListView.as_view(),name='teacher_list'),
    url(r'teacher_detail/(?P<teacher_id>.*)/$',TeacherDetailView.as_view(),name='teacher_detail'),
]+static(MEDIA_URL,document_root=MEDIA_ROOT)     #引入media

jyteaches/jyteaches/urls.py
from django.conf.urls import url,include
from django.contrib import admin
import xadmin
from django.views.generic import  TemplateView
from users.views import user_login,user_register,user_active,forget_pwd,user_reset,user_reset_post,user_logout,index_view,UserCenterInfoView,UploadImageView,UpdatePwdView
from users.views import SendEamilCodeView,UpdateEmailView,MyCourseView,MyFavOrgView,MyFavTeacherView,MyFavCourseView,MyMessageView
from jyteaches.settings import MEDIA_ROOT,MEDIA_URL,STATIC_ROOT  #
from django.conf.urls.static import static            #引入media及static
from django.views.static import serve

from django.conf import settings


urlpatterns = [
    url(r'^xadmin/', xadmin.site.urls),
    #url(r'^$',TemplateView.as_view(template_name='index.html'),name='index'),#不需要加视图函数
    url(r'^$',index_view.as_view(),name='index'),
    url(r'^login/$',user_login.as_view(),name='login'),
    url(r'logout/$',user_logout.as_view(),name='logout'),
    url(r'^register/$',user_register.as_view(),name='register'),
    url(r'^captcha',include('captcha.urls')),
    url(r'^active/(?P<active_code>.*)/$',user_active.as_view(),name='active'),
    url(r'^forgetpwd/$',forget_pwd.as_view(),name='forgetpwd'),
    url(r'^reset/(?P<reset_code>.*)/$',user_reset.as_view(),name='reset'),
    url(r'^resetmodify/$',user_reset_post.as_view(),name='resetmodify'),
    url(r'^org/',include('organizations.urls',namespace='org')),
                                            #命名空间（在页面中能用org：xxx）
    url(r'^course/',include('courses.urls',namespace='course')),
    url(r'^user_info/$',UserCenterInfoView.as_view(),name='user_info'),
    url(r'upload_image/$',UploadImageView.as_view(),name='upload_image'),
    url(r'update_pwd/$',UpdatePwdView.as_view(),name='update_pwd'),
    url(r'sendemail_code/$',SendEamilCodeView.as_view(),name='sendemail_code'),
    url(r'update_email/$',UpdateEmailView.as_view(),name='update_email'),
    url(r'my_course/$',MyCourseView.as_view(),name='my_course'),
    url('myfav_org/$',MyFavOrgView.as_view(),name='myfav_org'),
    url('myfav_teacher/$',MyFavTeacherView.as_view(), name='myfav_teacher'),
    url('myfav_course/$',MyFavCourseView.as_view(), name='myfav_course'),
    url(r'my_message/$',MyMessageView.as_view(),name='my_message'),

    url(r'^static/(?P<path>.*)$', serve, {'document_root':STATIC_ROOT}, name='static'),
    url(r'^media/(?P<path>.*)$', serve, {'document_root':MEDIA_ROOT}, name='media'),
]+static(MEDIA_URL,document_root=MEDIA_ROOT)     #引入media

jyteaches/apps/courses/models.py
from datetime import datetime
from django.db import models
from organizations.models import CourseOrg,Teacher


# Create your models here.
class Course(models.Model):
    name = models.CharField(max_length=50, verbose_name='课程名字')
    desc = models.CharField(max_length=200,verbose_name='课程描述')
    detail = models.TextField(verbose_name='课程详情')
    courtime = models.IntegerField(default=0,verbose_name='课程时长')
    click_nums = models.IntegerField(default=0,verbose_name='点击次数')
    fav_nums = models.IntegerField(default=0,verbose_name='收藏此书')
    image = models.ImageField(upload_to='courses/%Y/%m',verbose_name='课程封面')
    studies = models.IntegerField(default=0,verbose_name='学习人数')
    add_time = models.DateTimeField(default=datetime.now,verbose_name='登记时间')
    course_org = models.ForeignKey(CourseOrg,verbose_name='课程机构',null=True,blank=True)
    degree = models.CharField(max_length=20,choices=(('cj','初级'),('zj','中级'),('gj','高级')),verbose_name='课程难度',default='cj')
    category = models.CharField(max_length=30,verbose_name='课程类别',default='后台开发')
    tag = models.CharField(max_length=40,verbose_name='课程标签',default='服务器操作系统')
    annunciate = models.CharField(default='',verbose_name='课程通告',max_length=100)
    teacher = models.ForeignKey(Teacher,verbose_name='教师',null=True,blank=True)
    need_know = models.CharField(default='',verbose_name='课程须知',max_length=200)
    teacher_tell = models.CharField(default='',verbose_name='老师告诉你学到什么',max_length=200)

    class Meta:
        verbose_name = '课程详情'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

    def get_lesson_nums(self):  #计算课程外键的方法
        return self.lesson_set.all().count()

    def get_users(self):
        return self.usercourse_set.all()

    def get_lesson(self):
        return self.lesson_set.all()

    def get_resource(self):
        return self.courseresource_set.all()


class CourseResource(models.Model):
    name = models.CharField(max_length=50, verbose_name='资源名称')
    file = models.FileField(upload_to='courses/resource/%Y/%m',verbose_name='文件')
    add_time = models.DateTimeField(default=datetime.now,verbose_name='添加时间')
    course = models.ForeignKey(Course,verbose_name='对应课程')

    class Meta:
        verbose_name = '课程资源'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name


class Lesson(models.Model):
    name = models.CharField(max_length=50,verbose_name='章节名')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='登记时间')
    course = models.ForeignKey(Course,verbose_name='属于课程')

    class Meta:
        verbose_name = '章节详情'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name+self.course.name    #显示章节名加对应的课程

    def get_vidoe(self):
        return self.video_set.all()


class Video(models.Model):
    name = models.CharField(max_length=50,verbose_name='视频名称')
    add_time = models.DateTimeField(default=datetime.now, verbose_name='添加时间')
    lesson = models.ForeignKey(Lesson,verbose_name='对应章节')
    video = models.CharField(max_length=100,default='',verbose_name='视频地址')

    class Meta:
        verbose_name = '视频信息'
        verbose_name_plural = verbose_name

    def __str__(self):
        return self.name

jyteaches/apps/users/forms.py
from django import forms
from captcha.fields import CaptchaField
from .models import UserProfile


class Login_Form(forms.Form):
    username = forms.CharField(required=True) #不能为空,名字与前端的name名字一样
    password = forms.CharField(required=True,min_length=5,error_messages={"required":"密码错误"})


class Register_Form(forms.Form):
    email = forms.EmailField(required=True)
    password = forms.CharField(required=True,min_length=5)
    captcha = CaptchaField()


class ForgetPwd_Form(forms.Form):
    email = forms.EmailField(required=True)
    captcha = CaptchaField()

class ResetPwd_Form(forms.Form):
    password1 = forms.CharField(required=True,min_length=5)
    password2 = forms.CharField(required=True,min_length=5)

class UserInfo_Form(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ["nike_name","sex","birthday","address","mobile"]

class UploadImageForm(forms.ModelForm):
    class Meta:
        model = UserProfile
        fields = ["image"]

jyteaches/templates/course-detail.html
{% extends 'base.html' %}
{% load staticfiles%}
{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="/static/css/reset.css">
	<link rel="stylesheet" type="text/css" href="/static/css/animate.css">
	<link rel="stylesheet" type="text/css" href="/static/css/style.css">
{% endblock %}
{% block title %}
公开课列表 - 慕学在线网
{% endblock %}

{% block bread %}
   <section>
	<div class="wp">
		<div class="crumbs">
			<ul>
				<li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'course:course_list' %}">公开课程</a>></li>
				<li>课程详情</li>
			</ul>
		</div>
	</div>
</section>
{% endblock %}

{% block content %}
    <section>
	<div class="wp">
		<div class="groupPurchase_detail detail">
			<div class="toppro">
				<div class="left">
					<div class="picbox">
						<div class="tb-booth tb-pic">
							<img width="440" height="445" src="{{ MEDIA_URL }}{{ course.image }}" class="jqzoom" />
						</div>

					</div>
					<div class="des">
						<h1 title="django 从入门到精通体验开始了">{{ course.name }}</h1>
						<span class="key">{{ course.desc }}</span>
						<div class="prize">
							<span class="fl">难度：<i class="key">{{ course.get_degree_display}}</i></span>
							<span class="fr">学习人数：{{ course.studies }}</span>
						</div>
						<ul class="parameter">
							<li><span class="pram word3">时&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;长：</span><span>{{ course.courtime }}</span></li>
                            <li><span class="pram word3">章&nbsp;节&nbsp;数：</span><span>{{ course.get_lesson_nums }}</span></li>
                            <li><span class="pram word3">课程类别：</span><span title="">{{ course.category }}</span></li>
							<li class="piclist"><span class="pram word4">学习用户：</span>
                                {% for cuser in course.get_users %}
                                      <span class="pic"><img width="40" height="40" src="{{ MEDIA_URL }}{{ cuser.user.image }}"/></span>
                                {% endfor %}
							</li>
						</ul>
						<div class="btns">
							<div class="btn colectgroupbtn"  id="jsLeftBtn">
                                  {% if has_course_fav %}已收藏{% else %}收藏{% endif %}
                            </div>
                                <div class="buy btn"><a style="color: white" href="{% url 'course:course_video' course_id %}">开始学习</a></div>
						</div>
					</div>
                    <div class="group-share-box">
                        <div class="bdsharebuttonbox"
                             data-text="django开始了"
                             data-desc="我在#慕课网#发现了"
                             data-comment=""
                             data-url="/group/groupdetail/15/">
                            <span class="fl">分享到：</span>
<div class="bdsharebuttonbox"><a href="#" class="bds_more" data-cmd="more"></a><a href="#" class="bds_qzone" data-cmd="qzone" title="分享到QQ空间"></a><a href="#" class="bds_tsina" data-cmd="tsina" title="分享到新浪微博"></a><a href="#" class="bds_tqq" data-cmd="tqq" title="分享到腾讯微博"></a><a href="#" class="bds_renren" data-cmd="renren" title="分享到人人网"></a><a href="#" class="bds_weixin" data-cmd="weixin" title="分享到微信"></a></div>
<script>window._bd_share_config={"common":{"bdSnsKey":{},"bdText":"","bdMini":"2","bdMiniList":false,"bdPic":"","bdStyle":"0","bdSize":"24"},"share":{}};with(document)0[(getElementsByTagName('head')[0]||body).appendChild(createElement('script')).src='http://bdimg.share.baidu.com/static/api/js/share.js?v=89860593.js?cdnversion='+~(-new Date()/36e5)];</script>
                        </div>
                    </div>
				</div>
				<div class="right">
					<div class="head">
						<h1>授课机构</h1>
						<p>世界名校，课程权威</p>
					</div>
					<div class="pic">
                        <a href="{% url 'org:orghome' course.course_org.id %}">
                            <img width="150" height="80" src="{{ MEDIA_URL }}{{ course.course_org.image }}"/>
                        </a>
                    </div>
					<a href="{% url 'org:orghome' course.course_org.id %}">
                        <h2 class="center" title="{{ course.course_org }}">{{ course.course_org }}</h2>{# 因为__str__所以不用写name #}
                    </a>
					<div class="btn  notlogin" data-favid="14" id="jsRightBtn">
                        {% if has_org_fav %}已收藏{% else %}收藏{% endif %}
                    </div>
					<div class="clear">
						<ul>
                            <li>
                                <span>课 &nbsp;程&nbsp; 数：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;   {{ course.course_org.courses }}</span>
                            </li>
                            <li>
                                <span>教 &nbsp;师&nbsp; 数：&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;  {{ course.course_org.get_teacher_nums }}</span>
                            </li>
							<li>所在地区：&nbsp;&nbsp;{{ course.course_org.address }}</li>
							<li>认&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;证&nbsp;:
                                &nbsp;&nbsp;
								    <img title="金牌机构", src="{% static 'images/gold.png' %}"/>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</div>
	</div>
</section>
    <section>
	<div class="wp">
		<div class="list groupPurchase_detail_pro">
			<div class="left layout">
				<div class="head">
					<ul class="tab_header">
						<li class="active">课程详情</li>
					</ul>
                    {{ course.detail }}
				</div>
				<div class="tab_cont tab_cont2" >
					<div class="comment">
						<div class="comenlist">
	                    </div>
					</div>
				</div>
			</div>
			<div class="right layout">
				<div class="head">相关课程推荐</div>
                <div class="group_recommend">
                    {% for show_course in show_courses %}
                         <dl>
                            <dt>
                                <a target="_blank" href="{% url 'course:course_detail' show_course.id %}">
                                    <img width="240" height="220" class="scrollLoading" src="{{ MEDIA_URL }}{{ show_course.image }}"/>
                                </a>
                            </dt>
                            <dd>
                                <a target="_blank" href="{% url 'course:course_detail' show_course.id %}"><h2> {{ show_course.name }}</h2></a>
                                <span class="fl">学习时长：<i class="key">{{ show_course.courtime }}</i></span>
                            </dd>
                        </dl>
                    {% endfor %}



                </div>
			</div>
		</div>
	</div>
</section>

    {% block custom_js %}
        <script type="text/javascript">
//收藏分享
        function add_fav(current_elem, fav_id, fav_type){
            $.ajax({
                cache: false,
                type: "POST",
                url:"{% url 'org:add_fav' %}",
                data:{'fav_id':fav_id, 'fav_type':fav_type},
                async: true,
                beforeSend:function(xhr, settings){
                    xhr.setRequestHeader("X-CSRFToken", "{{ csrf_token  }}");
                },
                success: function(data) {
                    if(data.status == 'fail'){
                        if(data.msg == '用户未登录'){
                            window.location.href="{% url 'login' %}";
                        }else{
                            alert(data.msg)
                        }

                    }else if(data.status == 'success'){
                        current_elem.text(data.msg)
                    }
                },
            });
        }

        $('#jsLeftBtn').on('click', function(){
            add_fav($(this), {{ course.id }}, 1);
        });

        $('#jsRightBtn').on('click', function(){
            add_fav($(this), {{ course.course_org.id }}, 2);
        });

    </script>
    {% endblock %}
{% endblock %}

jyteaches/templates/course-list.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block title %}
公开课列表 - 慕学在线网
{% endblock %}

{% block bread %}
    <section>
        <div class="wp">
            <ul  class="crumbs">
                <li><a href="{% url 'index' %}">首页</a>></li>
                <li>公开课</li>
            </ul>
        </div>
    </section>
{% endblock %}

{% block content %}
    <section>
	<div class="wp">
		<div class="list" style="margin-top:0;">
			<div class="left layout">
				<div class="head">
					<ul class="tab_header">
						<li class="{% ifequal sort ''%}active{% endifequal %}"><a href="?sort=">最新 </a></li>
						<li class="{% ifequal sort 'hot'%}active{% endifequal %}"><a href="?sort=hot&keywords={{ keywords }}">最热门</a></li>
						<li class="{% ifequal sort 'students'%}active{% endifequal %}"><a href="?sort=students&keywords={{ keywords }}">参与人数</a></li>
					</ul>
				</div>
                <div id="inWindow">
                    <div class="tab_cont " id="content">
					<div class="group_list">
                            {% for course in all_courses.object_list %}
                                <div class="box">
                                <a href="{% url 'course:course_detail' course.id %}">
                                    <img width="280" height="350" class="scrollLoading" src="{{ MEDIA_URL }}{{ course.image }}"/>
                                </a>
                                <div class="des">
                                    <a href="{% url 'course:course_detail' course.id %}">
                                        <h2>{{ course.name }}</h2>
                                    </a>
                                    <span class="fl">时长：<i class="key">{{ course.courtime }}</i></span>
                                    <span class="fr">学习人数：{{ course.studies }}&nbsp;&nbsp;</span>
                                </div>
                                <div class="bottom">
                                    <a href=""><span class="fl">{{ course.course_org }}</span></a>
                                    <span class="star fr  notlogin
                                        " data-favid="15">
                                        1
                                    </span>
                                </div>
                            </div>
                            {% endfor %}

					</div>
                    <div class="pageturn">
                        <ul class="pagelist">
                            {% if all_courses.has_previous %}
                                <li class="long"><a href="?{{ all_courses.previous_page_number.querystring }}">上一页</a></li>
                            {% endif %}
                            {% for page in all_courses.pages %}
                            {% if page %}
                                {% ifequal page all_courses.number %}
                                         <li class="active">{{ page }}</li>
                                {% else %}
                                    <li class="page"><a href="?{{ page.querystring }}">{{ page }}</a></li>
                                {% endifequal %}
                            {% else %}
                                ...
                            {% endif %}
                            {% endfor %}
                            {% if all_courses.has_next %}
                                 <li class="long"><a href="?{{ all_courses.next_page_number.querystring  }}">下一页</a></li>
                            {% endif %}
                        </ul>
                    </div>
				</div>
                </div>
			</div>
			<div class="right layout">
				<div class="head">热门课程推荐</div>
				<div class="group_recommend">
                    {% for hot_course in hot_courses %}
                        <dl>
						<dt>
							<a target="_blank" href="{% url 'course:course_detail' hot_course.id %}">
								<img width="240" height="220" class="scrollLoading" src="{{ MEDIA_URL }}{{ hot_course.image }}"/>
							</a>
						</dt>
						<dd>
							<a target="_blank" href={% url 'course:course_detail' hot_course.id %}"><h2> {{ hot_course.name }}</h2></a>
							<span class="fl">难度：<i class="key">{{ hot_course.get_degree_display}}</i></span>
						</dd>
					</dl>
                    {% endfor %}

				</div>
			</div>
		</div>
	</div>
</section>
{% endblock %}

jyteaches/templates/course-video.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block custom_css %}
    <link rel="stylesheet" type="text/css" href="/static/css/muke/base.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/muke/common-less.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/muke/course/learn-less.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/aui.css" />
    <link rel="stylesheet" type="text/css" href="/static/css/mooc.css" />
     <link rel="stylesheet" type="text/css" href="/static/css/muke/course/common-less.css">
{% endblock %}

{% block title%}
    公开课信息-慕学在线网
{% endblock %}

{% block bread %}
    <section>
	<div class="wp">
		<div class="crumbs">
			<ul>
				<li><a href="{% url 'index' %}">首页</a>></li>
                <li><a href="{% url 'course:course_list' %}">公开课程</a>></li>
				<li><a href="{% url 'course:course_detail' course_id %}">课程详情</a>></li>
                <li>章节信息</li>
			</ul>
		</div>
	</div>
</section>
{% endblock %}

{% block content %}
    <div id="main">
    <div class="course-infos">
        <div class="w pr">
            <div style="height: 15px" class="path">
            </div>
            <div class="hd">
                <h2 class="l">{{ course.name }}</h2>
            </div>
            <div class="statics clearfix">
                <div class="static-item ">
                    <span class="meta-value"><strong>{{ course.get_degree_display }}</strong></span>
                    <span class="meta">难度</span>
                    <em></em>
                </div>
                <div class="static-item static-time">
                    <span class="meta-value">{{ course.courtime }}分钟</span>
                    <span class="meta">时长</span>
                    <em></em>
                </div>
                <div class="static-item">
                    <span class="meta-value"><strong>{{ course.studies }}</strong></span>
                    <span class="meta">学习人数</span>
                    <em></em>
                </div>
            </div>
        </div>
    </div>
    <div class="course-info-main clearfix w has-progress">

        <div class="info-bar clearfix">
        <div class="content-wrap clearfix">
            <div class="content">
                <div class="mod-tab-menu">
                    <ul class="course-menu clearfix">
                        <li><a class="ui-tabs-active active" id="learnOn"  href="{% url 'course:course_video' course_id %}"><span>章节</span></a></li>
                        <li><a id="commentOn" class="" href="{% url 'course:course_comment' course_id %}"><span>评论</span></a></li>
                    </ul>
                </div>
                <div id="notice" class="clearfix">
                    <div class="l"> <strong>课程公告:</strong> <a  href="javascript:void(0)">{{ course.annunciate }}</a> </div>
                </div>

                <div class="mod-chapters">
                    {% for lesson in course.get_lesson %}
                        <div class="chapter chapter-active" >
                        <h3>
                            <strong><i class="state-expand"></i>{{ lesson.name }}</strong>
                        </h3>
                        <ul class="video">
                            {% for video in lesson.get_vidoe %}
                                <li>
                                <a target="_blank" href='{{ MEDIA_URL }}{{ video.video }}' class="J-media-item studyvideo">{{ video.name }} (0)
                                    <i class="study-state"></i>
                                </a>
                            </li>
                            {% endfor %}

                        </ul>
                    </div>
                    {% endfor %}
                </div>

            </div>
            <div class="aside r">
                <div class="bd">

                    <div class="box mb40">
                        <h4>资料下载</h4>
                        <ul class="downlist">
                            {% for resource in course.get_resource %}
                                <li>
                                <span ><i class="aui-iconfont aui-icon-file"></i>&nbsp;&nbsp;{{ resource.name }}</span>
                                <a href="{{ MEDIA_URL }}{{ resource.file }}" class="downcode" target="_blank" download="" data-id="274" title="">下载</a>
                            </li>
                            {% endfor %}



                        </ul>
                    </div>
                    <div class="box mb40">
                        <h4>讲师提示</h4>
                        <div class="teacher-info">
                            <a href="/u/315464/courses?sort=publish" target="_blank">
                                <img src='{{ MEDIA_URL }}{{ course.teacher.image }}' width='80' height='80' />
                            </a>
        <span class="tit">
          <a href="/u/315464/courses?sort=publish" target="_blank">{{ course.teacher.name }}</a>
        </span>
                            <span class="job">{{ course.teacher.work_position }}</span>
                        </div>
                        <div class="course-info-tip">
                            <dl class="first">
                                <dt>课程须知</dt>
                                <dd class="autowrap">{{ course.need_know }}</dd>
                            </dl>
                            <dl>
                                <dt>老师告诉你能学到什么？</dt>
                                <dd class="autowrap">{{ course.teacher_tell }}</dd>
                            </dl>
                        </div>
                    </div>


                    <div class="cp-other-learned  js-comp-tabs">
                        <div class="cp-header clearfix">
                            <h2 class="cp-tit l">该课的同学还学过</h2>
                        </div>
                        <div class="cp-body">
                            <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="course" style="display: block">
                                <!-- img 200 x 112 -->
                                <ul class="other-list">
                                    {% for relative_course in all_relative_courses %}
                                        <li class="curr">
                                        <a href="{% url 'course:course_detail' relative_course.id%}" target="_blank">
                                            <img src="{{ MEDIA_URL }}{{ relative_course.image }}" alt="{{ relative_course.name }}">
                                            <span class="name autowrap">{{ relative_course.name }}</span>
                                        </a>
                                    </li>
                                    {% endfor %}



                                </ul>
                            </div>
                            <div class="cp-tab-pannel js-comp-tab-pannel" data-pannel="plan">
                                <ul class="other-list">
                                    <li class="curr">
                                        <a href="/course/programdetail/pid/31?src=sug" target="_blank">
                                            <img src="http://img.mukewang.com/56551e6700018b0c09600720-240-135.jpg" alt="Java工程师">
                                            <span class="name autowrap">Java工程师</span>
                                        </a>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>

                </div>    </div>
        </div>
        <div class="clear"></div>

    </div>

</div>
</div>
{% endblock %}